language: node_js
sudo: true
node_js:
  - 10
branches:
  - master
cache:
  directories:
    - node_modules
before_install:
  - npm i
script:
  - npm run build
  - npm run test
after_success:
  - npm run coverage